import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { AiOutlineArrowRight } from 'react-icons/ai';
import { AiOutlineEyeInvisible } from 'react-icons/ai';
import { MdKeyboardArrowDown } from 'react-icons/md';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/*  */}
        <div className="bg-white pb-6 sm:pb-8 lg:pb-12">
          <div className="max-w-screen-2xl px-4 md:px-8 mx-auto">
            <header className="flex justify-between items-center  py-4 md:py-8 mb-8 md:mb-12 xl:mb-16">
              {/* <!-- logo - start --> */}
              <a href="/" className="inline-flex items-center text-black-800 text-2xl md:text-3xl font-bold gap-2.5" aria-label="logo">
                <svg width="95" height="94" viewBox="0 0 95 94" className="w-6 h-auto text-indigo-500" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path d="M96 0V47L48 94H0V47L48 0H96Z" />
                </svg>

              </a>
              {/* <!-- logo - end --> */}


            </header>

            <section className="flex flex-col lg:flex-row justify-between gap-6 sm:gap-10 md:gap-16">
              {/* <!-- content - start --> */}
              <div className="xl:w-5/12 flex flex-col justify-between">
                <div></div>

                <div className="sm:text-center lg:text-left lg:py-12 xl:py-24">
                  <h1 className="text-black-800 text-4xl sm:text-5xl md:text-6xl font-bold mb-8 md:mb-12">Welcome to System package</h1>

                  {/* Form start */}
                  <form className="max-w-lg mx-auto">
                    <div className="flex flex-col gap-4 p-4 md:p-8">

                      <div className='relative'>
                        <input name="email" className="w-full bg-gray-50 text-black border focus:ring ring-indigo-300 rounded-lg outline-none transition duration-100 px-3 py-3 placeholder-black text-xl font-semibold" placeholder='hellouser' />
                        <div className='absolute inset-y-0 right-0 pr-3 flex items-center text-xl leading-5 text-gray-500'>
                          <button onclick="showDropdownOptions()" class="flex flex-row justify-between w-48 px-2 py-2 text-gray-700 bg-white border-2 border-white rounded-md shadow focus:outline-none focus:border-blue-600">
                            <span class="select-none">@heads.design</span>
                            <MdKeyboardArrowDown className='w-6 h-6' />
                          </button>
                        </div>
                      </div>



                      <div class="relative">
                        <input name="password" placeholder="" class="w-full bg-gray-50 border focus:ring ring-indigo-300 rounded-lg outline-none transition duration-100 px-3 py-3 placeholder-black text-xl font-semibold" />
                        <div class="absolute inset-y-0 right-0 pr-3 flex items-center text-xl leading-5 text-gray-500">
                          <AiOutlineEyeInvisible />
                        </div>
                      </div>


                      <Link href={'/otp'}><button className="block bg-[#0858F7] hover:bg-[#083796] active:bg-gray-600 focus-visible:ring ring-gray-300 text-white text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3 group relative "
                      >
                        Next
                        <p className='absolute top-4 right-[200px]'><AiOutlineArrowRight /></p>
                      </button></Link>
                      {/* 
                      <button className="block bg-[#0858F7] hover:bg-[#083796] active:bg-gray-600 focus-visible:ring ring-gray-300 text-white text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3 group"
                        style={{ clipPath: 'inset(0 0 0 0 )' }}
                      >
                        <div class="[grid-area:1/1] flex items-center justify-center h-10 w-10 transition ease-in-out group-hover:delay-300 translate-y-10 -translate-x-10 group-hover:translate-y-0 group-hover:translate-x-0 absolute left-[470px] bottom-[295px] text-[30px]">
                          &#8594;
                        </div>
                        Next</button> */}




                    </div>

                    <div className="flex justify-center items-center p-2">
                      <p className='text-[#0858F7] font-bold'>Forgot Your Password?</p>
                    </div>
                  </form>
                  {/* Form end */}

                </div>
              </div>
              {/* <!-- content - end --> */}

              {/* <!-- image - start --> */}
              <div className="xl:w-5/12 h-48 lg:h-auto bg-gray-100 overflow-hidden shadow-lg rounded-lg">
                <img src="https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?auto=format&q=75&fit=crop&w=1000" loading="lazy" alt="Photo by Fakurian Design" className="w-full h-full object-cover object-center" />
              </div>
              {/* <!-- image - end --> */}
            </section>
          </div>
        </div>
      </main>
    </>
  )
}
